// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMcuEVQqNTIaRbhwatYddXtqc_0hTV15E',
    appId: '1:638748047552:web:9424372c52e21df59f1525',
    messagingSenderId: '638748047552',
    projectId: 'pollo-2025-f4d01',
    authDomain: 'pollo-2025-f4d01.firebaseapp.com',
    storageBucket: 'pollo-2025-f4d01.firebasestorage.app',
    measurementId: 'G-SBZ9C07ZRP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfah7ygplX_Kr0uL_ziVR0hYd9oV-mYG0',
    appId: '1:638748047552:android:4d9fcd09ae0256229f1525',
    messagingSenderId: '638748047552',
    projectId: 'pollo-2025-f4d01',
    storageBucket: 'pollo-2025-f4d01.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBguvpJxJWXn3l1fWtpW9ssIJsIj2G9d2U',
    appId: '1:638748047552:ios:92f64e5ea23f8bc59f1525',
    messagingSenderId: '638748047552',
    projectId: 'pollo-2025-f4d01',
    storageBucket: 'pollo-2025-f4d01.firebasestorage.app',
    iosBundleId: 'com.waldirdev01.pollo2025',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBguvpJxJWXn3l1fWtpW9ssIJsIj2G9d2U',
    appId: '1:638748047552:ios:92f64e5ea23f8bc59f1525',
    messagingSenderId: '638748047552',
    projectId: 'pollo-2025-f4d01',
    storageBucket: 'pollo-2025-f4d01.firebasestorage.app',
    iosBundleId: 'com.waldirdev01.pollo2025',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMcuEVQqNTIaRbhwatYddXtqc_0hTV15E',
    appId: '1:638748047552:web:f919d30d1e4d3e7a9f1525',
    messagingSenderId: '638748047552',
    projectId: 'pollo-2025-f4d01',
    authDomain: 'pollo-2025-f4d01.firebaseapp.com',
    storageBucket: 'pollo-2025-f4d01.firebasestorage.app',
    measurementId: 'G-4CJQ20DH2D',
  );
}
